// Login Actions
export enum loginEnumActions {
    LOGIN_USER = "LOGIN_USER",
    LOGOUT_USER = "LOGOUT_USER"
}


// Movie Actions
export enum movieEnumActions {
    SEARCH_MOVIE_REQUEST = "SEARCH_MOVIE_REQUEST",
    SEARCH_MOVIE_SUCCESS = "SEARCH_MOVIE_SUCCESS",
    SEARCH_MOVIE_CHANGE_PAGE_REQUEST = "SEARCH_MOVIE_CHANGE_PAGE_REQUEST",
    SEARCH_MOVIE_CHANGE_PAGE_SUCCESS = "SEARCH_MOVIE_CHANGE_PAGE_SUCCESS",
    SEARCH_MOVIE_DETAIL_REQUEST = "SEARCH_MOVIE_DETAIL_REQUEST",
    SEARCH_MOVIE_DETAIL_SUCCESS = "SEARCH_MOVIE_DETAIL_SUCCESS",
    ADD_MOVIE_FAVORITE_CATEGORY = "ADD_MOVIE_FAVORITE_CATEGORY",
    GET_FAVORITES_MOVIES = "GET_FAVORITES_MOVIES",
};
